import { createElement } from 'lwc';
import Vmo_handleToTalTickets from 'c/vmo_handleToTalTickets';

describe('c-vmo-handle-to-tal-tickets', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-vmo-handle-to-tal-tickets', {
            is: Vmo_handleToTalTickets
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});